package com.github.integracao2017.cnes.cnesinterface;

/**
 * @author João Henrique
 * <p>
 *     Objetivo: marcar todas as chaves do HashMap
 *     da consulta das informações do(s) profissional(is)
 *     de saúde cadastrado no CNES.
 * </p>
 */

public enum ProfissionalSaudeService {

    //Operacao: consultarProfissionaisSaude
    /** DATA DE ATUALIZACAO DO REGISTRO - DATA.*/
    PROF_DATA_ATUALIZACAO("PROF_DATA_ATUALIZACAO"),
    /** NOME DO PROFISSIONAL DE SAUDE - TEXTO - MAX 15 CARACTERES.*/
    PROF_NOME("PROF_NOME"),
    /** CNS DO PROFISSIONAL DE SAUDE - TEXTO - MAX 15 CARACTERES.*/
    PROF_CNS_NUM("PROF_CNS_NUM"),
    /** DATA DE ATRIBUICAO DO CARTAO - DATA */
    PROF_CNS_DATA_ATRIB("PROF_CNS_DATA_ATRIB"),
    /** TIPO DO CARTAO: [P=Provisorio, D=Definitivo] - DOMINIO - MAX 7 CARACTERES */
    PROF_CNS_TIPO_CARTAO("PROF_CNS_TIPO_CARTAO"),
    /** IDENTIFICA SE O CARTAO FOI ADICIONADO MANUALMENTE- BOOLEANO */
    PROF_CNS_MANUAL("PROF_CNS_MANUAL"),
    /** JUSTIFICATIVA P/ ADICAO DO CARTAO MANUAL - TEXTO - MAX 200 CARATERES */
    PROF_CNS_JUST_MANUAL("PROF_CNS_JUST_MANUAL"),
    /** CPF DO PROFISSIONAL - TEXTO - MAX 11 CARACTERES */
    PROF_CPF("PROF_CPF"),
    /** CODIGO DO CBO DO PROFISSIONAL - NUMERICO - MAX 6 CARACTERES */
    PROF_COD_CBO("PROF_COD_CBO"),
    /** DESCRICAO DO CBO DO PROFISSIONAL - TEXTO - MAX 150 CARACTERES */
    PROF_DESC_CBO("PROF_DESC_CBO"),
    /** CODIGO DO ESTABELECIMENTO DE SAUDE - NUMERICO - MAX 7 CARACTERES */
    PROF_CNES_COD("PROF_CNES_COD"),
    /** NOME FANTASIA DO ESTABELECIMENTO DE SAUDE - TEXTO - MAX 150 CARACTERES */
    PROF_NOME_FANTASIA("PROF_NOME_FANTASIA"),
    /** CODIGO IDENTIFICADOR DO EMAIL - NUMERICO - MAX 1 CARACTERES */
    PROF_COD_IDENTIFICADOR_EMAIL("PROF_COD_IDENTIFICADOR_EMAIL"),
    /** ENDERECO DO EMAIL - TEXTO - MAX 100 CARACTERES */
    PROF_DESC_EMAIL("PROF_DESC_EMAIL"),
    /** TIPO DO EMAIL - TEXTO - MAX 1 CARACTERES */
    PROF_TIPO_EMAIL("PROF_TIPO_EMAIL"),
    /** EMAIL VALIDADO - BOOLEANO */
    PROF_EMAIL_VALIDADO("PROF_EMAIL_VALIDADO"),
    /** IDENTIFICADOR DO ENDEREÇO - NUMERICO */
    PROF_IDENTIF_ENDERECO("PROF_IDENTIF_ENDERECO"),
    /** TIPO DO ENDERECO - TEXTO - MAX 1 CARACTERES */
    PROF_TIPO_ENDERECO("PROF_TIPO_ENDERECO"),
    /** CODIGO DO TIPO LOGRADOURO - TEXTO - MAX 2 CARACTERES */
    PROF_COD_TIPO_LOGRADOURO("PROF_COD_TIPO_LOGRADOURO"),
    /** DESCRICAO DO TIPO LOGRADOURO - TEXTO - MAX 60 CARACTERES */
    PROF_DESC_TIPO_LOGRADOURO("PROF_DESC_TIPO_LOGRADOURO"),
    /** NOME DO LOGRADOURO - TEXTO - MAX 255 CARACTERES */
    PROF_NOME_LOGRADOURO("PROF_NOME_LOGRADOURO"),
    /** NUMERO DO LOGRADOURO - TEXTO - MAX 20 CARACTERES */
    PROF_NUM_LOGRADOURO("PROF_NUM_LOGRADOURO"),
    /** COMPLEMENTO DO LOGRADOURO - TEXTO - MAX 50 CARACTERES */
    PROF_COMPLEMENTO_LOGRADOURO("PROF_COMPLEMENTO_LOGRADOURO"),
    /** CODIGO DO BAIRRO - NUMERICO - MAX 8 CARACTERES */
    PROF_CODIGO_BAIRRO("PROF_CODIGO_BAIRRO"),
    /** DESCRICAO DO BAIRRO - TEXTO - MAX 255 CARACTERES */
    PROF_DESC_BAIRRO("PROF_DESC_BAIRRO"),
    /** CEP - NUMERICO - MAX 8 CARACTERES */
    PROF_COD_CEP("PROF_COD_CEP"),
    /** CODIGO DO MUNICIPIO - NUMERICO - MAX 7 CARACTERES */
    PROF_COD_MUNICIPIO("PROF_COD_MUNICIPIO"),
    /** NOME DO MUNICIPIO - TEXTO - MAX 60 CARACTERES */
    PROF_NOME_MUNICIPIO("PROF_NOME_MUNICIPIO"),
    /** CODIGO DA UF - TEXTO - MAX 2 CARACTERES */
    PROF_COD_UF("PROF_COD_UF"),
    /** SIGLA DA UF - TEXTO - MAX 2 CARACTERES */
    PROF_SIGLA_UF("PROF_SIGLA_UF"),
    /** CODIGO DA REGIAO (MACRORREGIAO) - TEXTO - MAX 4 CARACTERES */
    PROF_COD_REGIAO("PROF_COD_REGIAO"),
    /** NOME DA UF - TEXTO - MAX 60 CARACTERES */
    PROF_NOME_UF("PROF_NOME_UF"),
    /** CODIGO DO PAIS (SAI E SIH) - NUMERICO - MAX 3 CARACTERES */
    PROF_COD_PAIS("PROF_COD_PAIS"),
    /** CODIGO DO PAIS ANTIGO - NUMERICO - MAX 3 CARACTERES */
    PROF_COD_PAIS_ANTIGO("PROF_COD_PAIS_ANTIGO"),
    /** NOME DO PAIS - NUMERICO - MAX 60 CARACTERES */
    PROF_NOME_PAIS("PROF_NOME_PAIS"),
    /** NOME DO MUNICIPIO INTERNACIONAL - TEXTO - MAX 70 CARACTERES */
    PROF_MUNICIPIO_INTERNACIONAL("PROF_MUNICIPIO_INTERNACIONAL");

    /** Variavel para guardar o valor do campo.*/
    private String chave;

    /**@return Nome do campo.*/
    public String getChave() {
        return chave;
    }

    /**@param e - Nome do campo.*/
    ProfissionalSaudeService(String e) {
        chave = e;
    }
}
