package com.github.integracao2017.cnes.cnesinterface;

/**
 * @author João Henrique
 * <p>
 *     Objetivo: marcar todas as chaves do HashMap
 *     da consulta das informações do(s) profissional(is)
 *     de saúde cadastrado no CNES.
 * </p>
 */

public enum ProfissionalSaudeService {

    //Operação: consultarProfissionaisSaude
    /** DATA DE ATUALIZAÇÃO DO REGISTRO - DATA.*/
    PROF_DATA_ATUALIZACAO("PROF_DATA_ATUALIZACAO"),
    /** NOME DO PROFISSIONAL DE SAÚDE - TEXTO - MÁX 15 CARACTERES.*/
    PROF_NOME("PROF_NOME"),
    /** CNS DO PROFISSIONAL DE SAÚDE - TEXTO - MÁX 15 CARACTERES.*/
    PROF_CNS_NUM("PROF_CNS_NUM"),
    /** DATA DE ATRIBUIÇÃO DO CARTÃO - DATA */
    PROF_CNS_DATA_ATRIB("PROF_CNS_DATA_ATRIB"),
    /** TIPO DO CARTÃO: [P=Provisório, D=Definitivo] - DOMÍNIO - MÁX 7 CARACTERES */
    PROF_CNS_TIPO_CARTAO("PROF_CNS_TIPO_CARTAO"),
    /** IDENTIFICA SE O CARTÃO FOI ADICIONADO MANUALMENTE- BOOLEANO */
    PROF_CNS_MANUAL("PROF_CNS_MANUAL"),
    /** JUSTIFICATIVA P/ ADIÇÃO DO CARTÃO MANUAL - TEXTO - MÁX 200 CARATERES */
    PROF_CNS_JUST_MANUAL("PROF_CNS_JUST_MANUAL"),
    /** CPF DO PROFISSIONAL - TEXTO - MÁX 11 CARACTERES */
    PROF_CPF("PROF_CPF"),
    /** CÓDIGO DO CBO DO PROFISSIONAL - NUMÉRICO - MÁX 6 CARACTERES */
    PROF_COD_CBO("PROF_COD_CBO"),
    /** DESCRIÇÃO DO CBO DO PROFISSIONAL - TEXTO - MÁX 150 CARACTERES */
    PROF_DESC_CBO("PROF_DESC_CBO"),
    /** CÓDIGO DO ESTABELECIMENTO DE SAÚDE - NUMÉRICO - MÁX 7 CARACTERES */
    PROF_CNES_COD("PROF_CNES_COD"),
    /** NOME FANTASIA DO ESTABELECIMENTO DE SAÚDE - TEXTO - MÁX 150 CARACTERES */
    PROF_NOME_FANTASIA("PROF_NOME_FANTASIA"),
    /** CÓDIGO IDENTIFICADOR DO EMAIL - NUMÉRICO - MÁX 1 CARACTERES */
    PROF_COD_IDENTIFICADOR_EMAIL("PROF_COD_IDENTIFICADOR_EMAIL"),
    /** ENDEREÇO DO EMAIL - TEXTO - MÁX 100 CARACTERES */
    PROF_DESC_EMAIL("PROF_DESC_EMAIL"),
    /** TIPO DO EMAIL - TEXTO - MÁX 1 CARACTERES */
    PROF_TIPO_EMAIL("PROF_TIPO_EMAIL"),
    /** EMAIL VALIDADO - BOOLEANO */
    PROF_EMAIL_VALIDADO("PROF_EMAIL_VALIDADO"),
    /** IDENTIFICADOR DO ENDEREÇO - NUMÉRICO */
    PROF_IDENTF_ENDERECO("PROF_IDENTF_ENDERECO"),
    /** TIPO DO ENDEREÇO - TEXTO - MÁX 1 CARACTERES */
    PROF_TIPO_ENDEREÇO("PROF_TIPO_ENDEREÇO"),
    /** CÓDIGO DO TIPO LOGRADOURO - TEXTO - MÁX 2 CARACTERES */
    PROF_COD_TIPO_LOGRADOURO("PROF_COD_TIPO_LOGRADOURO"),
    /** DESCRIÇÃO DO TIPO LOGRADOURO - TEXTO - MÁX 60 CARACTERES */
    PROF_DESC_TIPO_LOGRADOURO("PROF_DESC_TIPO_LOGRADOURO"),
    /** NOME DO LOGRADOURO - TEXTO - MÁX 255 CARACTERES */
    PROF_NOME_LOGRADOURO("PROF_NOME_LOGRADOURO"),
    /** NÚMERO DO LOGRADOURO - TEXTO - MÁX 20 CARACTERES */
    PROF_NUM_LOGRADOURO("PROF_NUM_LOGRADOURO"),
    /** COMPLEMENTO DO LOGRADOURO - TEXTO - MÁX 50 CARACTERES */
    PROF_COMPLEMENTO_LOGRADOURO("PROF_COMPLEMENTO_LOGRADOURO"),
    /** CÓDIGO DO BAIRRO - NUMÉRICO - MÁX 8 CARACTERES */
    PROF_CODIGO_BAIRRO("PROF_CODIGO_BAIRRO"),
    /** DESCRIÇÃO DO BAIRRO - TEXTO - MÁX 255 CARACTERES */
    PROF_DESC_BAIRRO("PROF_DESC_BAIRRO"),
    /** CEP - NUMÉRICO - MÁX 8 CARACTERES */
    PROF_COD_CEP("PROF_COD_CEP"),
    /** CÓDIGO DO MUNICÍPIO - NUMÉRICO - MÁX 7 CARACTERES */
    PROF_COD_MUNICIPIO("PROF_COD_MUNICIPIO"),
    /** NOME DO MUNICÍPIO - TEXTO - MÁX 60 CARACTERES */
    PROF_NOME_MUNICIPIO("PROF_NOME_MUNICIPIO"),
    /** CÓDIGO DA UF - TEXTO - MÁX 2 CARACTERES */
    PROF_COD_UF("PROF_COD_UF"),
    /** SIGLA DA UF - TEXTO - MÁX 2 CARACTERES */
    PROF_SIGLA_UF("PROF_SIGLA_UF"),
    /** CÓDIGO DA REGIÃO (MACRORREGIÃO) - TEXTO - MÁX 4 CARACTERES */
    PROF_COD_REGIAO("PROF_COD_REGIAO"),
    /** NOME DA UF - TEXTO - MÁX 60 CARACTERES */
    PROF_NOME_UF("PROF_NOME_UF"),
    /** CÓDIGO DO PAÍS (SAI E SIH) - NUMÉRICO - MÁX 3 CARACTERES */
    PROF_COD_PAÍS("PROF_COD_PAÍS"),
    /** CÓDIGO DO PAÍS ANTIGO - NUMÉRICO - MÁX 3 CARACTERES */
    PROF_COD_PAÍS_ANTIGO("PROF_COD_PAÍS_ANTIGO"),
    /** NOME DO PAÍS - NUMÉRICO - MÁX 60 CARACTERES */
    PROF_NOME_PAÍS("PROF_NOME_PAÍS"),
    /** NOME DO MUNICÍPIO INTERNACIONAL - TEXTO - MÁX 70 CARACTERES */
    PROF_MUNICIPIO_INTERNACIONAL("PROF_MUNICIPIO_INTERNACIONAL");

    /** Variavel para guardar o valor do campo.*/
    private String chave;

    /**@return Nome do campo.*/
    public String getChave() {
        return chave;
    }

    /**@param e - Nome do campo.*/
    ProfissionalSaudeService(String e) {
        chave = e;
    }
}
