package com.github.integracao2017.cnes.cnesinterface;

/**
 * @author pedro.lopes
 * <p>
 *     Objetivo: marcar todas as chaves do HashMap
 *     da consulta da vinculacao do profissional de saude.
 * </p>
 */

public enum VinculacaoProfissionalService {

    //Operacao: detalharVinculacaoProfissionalSaude
    /** NOME DO PROFISSIONAL DE SAUDE - TEXTO - MAX 150 CARACTERES.*/
    PROF_NOME("PROF_NOME"),
    /** CPF DO PROFISSIONAL DE SAUDE - TEXTO - MAX 15 CARACTERES.*/
    PROF_CPF("PROF_CPF"),
    /** CNS DO PROFISSIONAL DE SAUDE - TEXTO - MAX 15 CARACTERES.*/
    PROF_CNS_NUM("PROF_CNS_NUM"),
    /** DATA DE ATRIBUICAO DO CARTAO - DATA */
    PROF_CNS_DATA_ATRIB("PROF_CNS_DATA_ATRIB"),
    /** TIPO DO CARTAO: [P=Provisorio, D=Definitivo] - DOMINIO - MAX 7 CARACTERES */
    PROF_CNS_TIPO_CARTAO("PROF_CNS_TIPO_CARTAO"),
    /** IDENTIFICA SE O CARTAO FOI ADICIONADO - BOOLEANO */
    PROF_CNS_MANUAL("PROF_CNS_MANUAL"),
    /** JUSTIFICATIVA P/ ADICAO DO CARTAO MANUAL - TEXTO - MAX 200 CARATERES */
    PROF_CNS_JUST_MANUAL("PROF_CNS_JUST_MANUAL"),
    /** CODIGO CNES DO ESTABELIECIMENTO - TEXTO - MAX 7 CARACTERES */
    CODIGO_CNES("CODIGO_CNES"),
    /** NOME FANTASIA DO ESTABELECIMENTO - TEXTO - MAX 150 CARACTERES */
    NOME_FANTASIA("NOME_FANTASIA"),
    /** CODIGO IDENTIFICADOR DA VINCULACAO - TEXTO - MAX 8 CARACTERES */
    VINCULACAO_IND("VINCULACAO_IND"),
    /** CODIGO DA MODALIDADE DO VINCULO - TEXTO - MAX 8 CARACTERES */
    VINCULO_COD_MOD("VINCULO_COD_MOD"),
    /** DESCRICAO DA MODALIDADE DO VINCULO - TEXTO - MAX 100 CARACTERES */
    VINCULO_COD_MOD_DESC("VINCULO_COD_MOD_DESC"),
    /** CODIGO DO TIPO DA MODALIDADE DO VINCULO - TEXTO - MAX 8 CARACTERES */
    VINCULO_COD_MOD_TIPO("VINCULO_COD_MOD_TIPO"),
    /** DESCRICAO DO TIPO DA MODALIDADE DO VINCULO - TEXTO - MAX 100 CARACTERES */
    VINCULO_COD_MOD_TIPO_DESC("VINCULO_COD_MOD_TIPO_DESC"),
    /** CODIGO DO SUBTIPO DA MODALIDADE DO VINCULO - TEXTO - MAX 8 CARACTERES */
    VINCULO_COD_MOD_SUB_TIPO("VINCULO_COD_MOD_SUB_TIPO"),
    /** DESCRICAO DO SUBTIPO DA MODALIDADE DO VINCULO - TEXTO - MAX 100 CARACTERES */
    VINCULO_COD_MOD_SUB_TIPO_DESC("VINCULO_COD_MOD_SUB_TIPO_DESC"),
    /** CODIGO IDENTIFICADOR DO CBO */
    CBO_COD("CBO_COD"),
    /** DESCRICAO DO CBO */
    CBO_DESC("CBO_DESC"),
    /** CARGA HORARIA AMBULATORIAL DO PROFISSIONAL NO ESTABELECIMENTO */
    QTD_CARGA_HR_AMUBULATOTIAL("QTD_CARGA_HR_AMUBULATOTIAL"), //NOME (AMBULATORIAL) ESCRITO ERRONEAMENTE NO DOCUMENTO DO CNES
    /** CARGA HORARIA DE OUTROS TIPOS DO PROFISSIONAL NO ESTABELECIMENTO */
    QTD_CARGA_HR_OUTROS("QTD_CARGA_HR_OUTROS"),
    /** CARGA HORARIA HOSPITAL SUS */
    QTD_CARGA_HR_HOSP_SUS("QTD_CARGA_HR_HOSP_SUS"),
    /** DATA DE INICIO DO VINCULO */
    COMPT_INICIO("COMPT_INICIO"),
    /** DATA DE TERMINO DO VINCULO */
    COMPT_FIM("COMPT_FIM"),

    /** VARIAVEIS QUE NAO EXISTEM ACIMA */
    //Operacao: pesquisarVinculacaoProfissionalSaude
    /** POSICAO INICIAL DO REGISTRO NA PAGINACAO - NUMERICO - MAX 7 CARACTERES */
    PAG_POS_INICIAL_REGISTRO("PAG_POS_INICIAL_REGISTRO"),
    /** QUANTIDADE DE REGISTROS POR PAGINA - NUMERICO - MAX 7 CARACTERES */
    PAG_QTD_REGISTROS("PAG_QTD_REGISTROS"),
    /** QUANTIDADE TOTAL DE REGISTROS - NUMERICO - MAX 7 CARACTERES */
    PAG_TOTAL_REGISTROS("PAG_TOTAL_REGISTROS");


    /** Variavel para guardar o valor do campo.*/
    private String chave;

    /**@return Nome do campo.*/
    public String getChave() {
        return chave;
    }

    /**@param e - Nome do campo.*/
    VinculacaoProfissionalService(String e) {
        chave = e;
    }

}